[project]
name = "bagging"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.3.2",
    "scikit-learn>=1.7.1",
    "tqdm>=4.67.1",
]
